### ISSUE TITLE
Оптимизация работы светодиодной ленты на базе чипов WS2818, WS2811, WS2813

### ISSUE THREAD

**Issue by Sheredeka** [Pshatsillo/mega_hacs#11]
Было бы славно довести до ума работу со светодиодной лентой с чипами WS2818, WS2811, WS2813

**Пожелание 1:** После перезапуска интеграции или всего НА лента должна быть выключена - в данный момент она всегда во включенном состоянии, просто яркость = 0
**Пожелание 2:** Добавить возможность управлять блоком питания ленты, т.к. нет смысла держать его включенным когда лента выключена. _Без этой возможности приходится костылить автоматизацию типа: если Включилась лента следует Включить блок питания, подождать 1 секунду (необходимо для того что бы лента могла принимать параметры для светодиодов), увеличить яркость на 1 и сразу уменьшить яркость на 1 - иначе лента не будет светиться ввиду того что команда с параметрами отправлялась до того как появилось питание._  Если не заморачиваться с добавлением БП в конфиг интеграции - то нужно просто через 1-2 секунды после включения ленты продублировать отправку параметров - за это время на ленту уже поступит питание.

Мой конфиг ленты:
```
mega:
  mega1:
    led:
      mega1_29_led:
        ws28xx: true
        port: 29
        order: brg
        chip: 138
```

Автоматизация для включения блока питания (light.mega1_29_led - лента, light.mega1_40e07 - блок питания) :
```
- id: '1641723820742'
  alias: Включение БП по включению ленты
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - light.mega1_29_led
    to: 'on'
  conditions:
  - condition: state
    entity_id: light.mega1_40e07
    state: 'off'
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.mega1_40e07
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - alias: Увеличить и уменьшить яркость на 1% если яркость меньше 100%
    if:
    - condition: numeric_state
      entity_id: light.mega1_29_led
      attribute: brightness
      below: 100
    then:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_step_pct: 1
      target:
        entity_id: light.mega1_29_led
    - action: light.turn_on
      metadata: {}
      data:
        brightness_step_pct: -1
      target:
        entity_id: light.mega1_29_led
  - alias: Уменьшить и увеличить яркость на 1% если яркость больше 99%
    if:
    - condition: numeric_state
      entity_id: light.mega1_29_led
      attribute: brightness
      above: 99
    then:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_step_pct: -1
      target:
        entity_id: light.mega1_29_led
    - action: light.turn_on
      metadata: {}
      data:
        brightness_step_pct: 1
      target:
        entity_id: light.mega1_29_led
  mode: single
```
